set-option -g @nest_depth 0

# --- C-n na aktywnej (root) warstwie: wyłącz się ---
bind -T root C-n \
  set-option -g @nest_depth 1 \;\
  set-option -g prefix None \;\
  set-option -g key-table off \;\
  set -g status-style bg=colour240,fg=black \;\
  set -g status-left-style fg=black,bg=colour235 \;\
  set -g status-right-style fg=black,bg=colour235 \;\
  set -g window-status-style fg=black,bg=colour240 \;\
  set -g window-status-current-style fg=colour240,bg=black \;\
  #set-option -g status off \;\
  refresh-client -S

# --- C-n na wyłączonej warstwie: licz i przekaż dalej ---
bind -T off C-n \
  run-shell "tmux set-option -g @nest_depth #{e|+:#{@nest_depth},1}" \;\
  send-keys -H 0e

# --- C-p na wyłączonej warstwie: czy to ja jestem "ostatnia"? ---
bind -T off C-p \
  if-shell -F "#{==:#{@nest_depth},1}" \
    "set -gu @nest_depth ; set -gu prefix ; set -gu key-table ; set -g status-style bg=green,fg=black ; set -g status-left-style fg=black,bg=white ; set -g status-right-style fg=black,bg=white ; set -g window-status-style fg=black,bg=green ; set -g window-status-current-style fg=green,bg=black ; refresh-client -S" \
    "run-shell 'tmux set -g @nest_depth #{e|-:#{@nest_depth},1}' ; send-keys -H 10"
